---
- name: Add apt key
  apt_key:
    url: "{{ url }}"
    state: present
  when: url != ""

- name: add repository
  apt_repository:
    repo: "{{ repo }}"
    state: present
    filename: "{{ package }}.list"
  when: repo != ""

# tasks file for package_ubuntu
